# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\acer\Desktop\thysys\thysys_assessmentPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(668, 489)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.icon = QtWidgets.QLabel(Form)
        self.icon.setGeometry(QtCore.QRect(270, 30, 161, 141))
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("c:\\Users\\acer\\Desktop\\thysys\\thyroid.png"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.thysysName = QtWidgets.QLabel(Form)
        self.thysysName.setGeometry(QtCore.QRect(300, 170, 111, 31))
        self.thysysName.setStyleSheet("color: rgb(255, 85, 127);\n"
"font: 87 14pt \"Arial Black\";\n"
"")
        self.thysysName.setObjectName("thysysName")
        self.Question = QtWidgets.QLabel(Form)
        self.Question.setGeometry(QtCore.QRect(120, 240, 461, 16))
        self.Question.setObjectName("Question")
        self.Answer2 = QtWidgets.QPushButton(Form)
        self.Answer2.setGeometry(QtCore.QRect(420, 290, 181, 51))
        self.Answer2.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 11pt \"Arial\";\n"
"border-radius: 15px;")
        self.Answer2.setObjectName("Answer2")
        self.Answer1 = QtWidgets.QPushButton(Form)
        self.Answer1.setGeometry(QtCore.QRect(80, 290, 181, 51))
        self.Answer1.setStyleSheet("background-color: rgb(170, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Arial\";\n"
"border-radius: 15px;")
        self.Answer1.setObjectName("Answer1")
        self.Answer3 = QtWidgets.QPushButton(Form)
        self.Answer3.setGeometry(QtCore.QRect(250, 380, 181, 51))
        self.Answer3.setStyleSheet("background-color: rgb(255, 85, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 11pt \"Arial\";\n"
"border-radius: 15px;")
        self.Answer3.setObjectName("Answer3")
        self.Back = QtWidgets.QPushButton(Form)
        self.Back.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.Back.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 170, 255);\n"
"border-radius:20px;")
        self.Back.setObjectName("Back")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 460, 291, 16))
        self.label_3.setStyleSheet("color: rgb(188, 188, 188);")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.thysysName.setText(_translate("Form", "THY-SYS"))
        self.Question.setText(_translate("Form", "[Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum]"))
        self.Answer2.setText(_translate("Form", "Answer 2"))
        self.Answer1.setText(_translate("Form", "Answer 1"))
        self.Answer3.setText(_translate("Form", "Answer 3"))
        self.Back.setText(_translate("Form", "Back"))
        self.label_3.setText(_translate("Form", "© Icon from flaticon.com"))
